#!/bin/bash

BLAH=rababarabarabarara

echo BLAH is $BLAH
echo 'the result of ##*ba is' ${BLAH##*ba}
echo 'the result of #*ba is' ${BLAH#*ba}
echo 'the result of %%ba* is' ${BLAH%%ba*}
echo 'the result of %ba* is' ${BLAH%ba*}







